### ISSUE TITLE
GSOC 2020

### ISSUE THREAD

**Issue by pwned-17** [0x4D31/quick#1]
Hello, @0x4D31  I would like to contribute to this project as it seems interesting and challenging. I currently have a very surfaced knowledge of Go and quick protocol. I would like to know what are some of the issues that  I can work on and start gaining momentum.

**Comment by 0x4D31** [comment]
Hi, thanks for your interest in this project. Please join the honeynet project’s GSoC slack, #2020-quick! We can chat about it there. https://gsoc-slack.honeynet.org/
